spring.application.name=kafka-producer

spring.kafka.producer.bootstrap-servers=localhost:9092

# STRING Serializer for Producer Value
spring.kafka.producer.string.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.string.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# JSON Serializer for Producer Value
spring.kafka.producer.json.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.json.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# TOPIC Names
kafka.string.topic.name=topic_string
kafka.json.topic.name=topic_json